In [4]:
import keras
from keras.models import Sequential  
from keras import layers
from keras.layers import Dense  
import numpy
import pandas as pd  

import warnings
warnings.filterwarnings("ignore")

In [10]:
name_columns = ['Sexo', 'Largura', 'Diámetro', 'Altura', 'Whole_weight', 'Shucked_weight', 'Viscera_weight', 'Shell_weight','Anillos']

dataset = pd.read_csv("C:/Users/Jose Manuel/Documents/VisualStudioCode_Workspace/Repo_CEDAPY/CEDAPY_25_26/ANALISIS_DATOS_PYTHON/NOTEBOOKS/EJERCICIOS/RN/abalone.data",
                        delimiter=",", header=None, names=name_columns)
display(dataset)

,Sexo,Largura,Diámetro,Altura,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Anillos
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [11]:
map_target_class = {'M': 0, 'F': 1, 'I':3}
dataset['Sexo']= dataset['Sexo'].map(map_target_class)
dataset.head()

,Sexo,Largura,Diámetro,Altura,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Anillos
0,0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,0,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [13]:
X = dataset.iloc[:,0:8]  
Y = dataset.iloc[:,8]

In [14]:
print(X.shape)
print(Y.shape)

(4177, 8)
(4177,)

In [15]:
model2 = keras.Sequential([
    keras.layers.Input(shape=(8,)),
    keras.layers.Dense(12, activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')    
])

In [16]:
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
model2.fit(X, Y, epochs=150, batch_size=10)

Epoch 1/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 905us/step - accuracy: 2.3941e-04 - loss: -48.7533
Epoch 2/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 2.3941e-04 - loss: -1035.2560
Epoch 3/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 2.3941e-04 - loss: -4854.3394
Epoch 4/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 2.3941e-04 - loss: -12738.6465
Epoch 5/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 2.3941e-04 - loss: -25449.2441
Epoch 6/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 2.3941e-04 - loss: -43494.3555
Epoch 7/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 2.3941e-04 - loss: -67216.8281
Epoch 8/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 842us/step - accuracy: 2.3941e-04 - loss: -96947.9453
Epoch 9/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 2.3941e-04 - loss: -132979.9531
Epoch 10/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 2.3941e-04 - loss: -175474.0000
Epoch 11/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 2.3941e-04 - loss: -224840.4688
Epoch 12/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 2.3941e-04 - loss: -281360.0000
Epoch 13/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 858us/step - accuracy: 2.3941e-04 - loss: -345240.2500
Epoch 14/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 2.3941e-04 - loss: -416844.5938
Epoch 15/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 2.3941e-04 - loss: -496383.4062
Epoch 16/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 2.3941e-04 - loss: -584123.5000
Epoch 17/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 2.3941e-04 - loss: -680419.8125
Epoch 18/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 2.3941e-04 - loss: -785561.4375
Epoch 19/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 2.3941e-04 - loss: -899882.8125
Epoch 20/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 2.3941e-04 - loss: -1023701.6250
Epoch 21/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 2.3941e-04 - loss: -1157235.8750
Epoch 22/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 2.3941e-04 - loss: -1300773.7500
Epoch 23/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 2.3941e-04 - loss: -1454505.1250
Epoch 24/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 2.3941e-04 - loss: -1618762.6250
Epoch 25/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -1793750.2500
Epoch 26/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 2.3941e-04 - loss: -1980119.1250
Epoch 27/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 2.3941e-04 - loss: -2177840.5000
Epoch 28/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 2.3941e-04 - loss: -2387359.7500
Epoch 29/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 2.3941e-04 - loss: -2609189.2500
Epoch 30/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 2.3941e-04 - loss: -2843346.7500
Epoch 31/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 2.3941e-04 - loss: -3090081.2500
Epoch 32/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 2.3941e-04 - loss: -3349721.5000
Epoch 33/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 868us/step - accuracy: 2.3941e-04 - loss: -3622942.7500
Epoch 34/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 2.3941e-04 - loss: -3909313.2500
Epoch 35/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 2.3941e-04 - loss: -4209613.0000
Epoch 36/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 2.3941e-04 - loss: -4524178.5000
Epoch 37/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 2.3941e-04 - loss: -4853074.0000
Epoch 38/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 2.3941e-04 - loss: -5196558.0000
Epoch 39/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 2.3941e-04 - loss: -5554622.5000
Epoch 40/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -5927939.5000
Epoch 41/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 2.3941e-04 - loss: -6316583.5000
Epoch 42/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -6721169.5000
Epoch 43/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 2.3941e-04 - loss: -7142245.0000
Epoch 44/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 2.3941e-04 - loss: -7579269.0000
Epoch 45/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 2.3941e-04 - loss: -8032722.5000
Epoch 46/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 2.3941e-04 - loss: -8503224.0000
Epoch 47/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 2.3941e-04 - loss: -8991066.0000
Epoch 48/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 2.3941e-04 - loss: -9496616.0000
Epoch 49/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -10019955.0000
Epoch 50/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 945us/step - accuracy: 2.3941e-04 - loss: -10561188.0000
Epoch 51/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -11120678.0000
Epoch 52/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -11698536.0000
Epoch 53/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 2.3941e-04 - loss: -12295225.0000
Epoch 54/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 2.3941e-04 - loss: -12911240.0000
Epoch 55/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 2.3941e-04 - loss: -13546866.0000
Epoch 56/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 2.3941e-04 - loss: -14203266.0000
Epoch 57/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 2.3941e-04 - loss: -14878322.0000
Epoch 58/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 2.3941e-04 - loss: -15574260.0000
Epoch 59/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 2.3941e-04 - loss: -16290984.0000
Epoch 60/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 2.3941e-04 - loss: -17028636.0000
Epoch 61/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 2.3941e-04 - loss: -17787268.0000
Epoch 62/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 2.3941e-04 - loss: -18566852.0000
Epoch 63/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 2.3941e-04 - loss: -19368514.0000
Epoch 64/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 2.3941e-04 - loss: -20191914.0000
Epoch 65/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 2.3941e-04 - loss: -21037412.0000
Epoch 66/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 2.3941e-04 - loss: -21905442.0000
Epoch 67/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 2.3941e-04 - loss: -22797248.0000
Epoch 68/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 2.3941e-04 - loss: -23711608.0000
Epoch 69/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 2.3941e-04 - loss: -24648038.0000
Epoch 70/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 2.3941e-04 - loss: -25608636.0000
Epoch 71/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 2.3941e-04 - loss: -26594388.0000
Epoch 72/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 2.3941e-04 - loss: -27603642.0000
Epoch 73/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 2.3941e-04 - loss: -28636946.0000
Epoch 74/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 2.3941e-04 - loss: -29694952.0000
Epoch 75/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 2.3941e-04 - loss: -30777850.0000
Epoch 76/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 2.3941e-04 - loss: -31886482.0000
Epoch 77/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 874us/step - accuracy: 2.3941e-04 - loss: -33020142.0000
Epoch 78/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 2.3941e-04 - loss: -34180588.0000
Epoch 79/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 2.3941e-04 - loss: -35367132.0000
Epoch 80/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 2.3941e-04 - loss: -36581436.0000
Epoch 81/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 2.3941e-04 - loss: -37822412.0000
Epoch 82/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 2.3941e-04 - loss: -39089404.0000
Epoch 83/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 2.3941e-04 - loss: -40383116.0000
Epoch 84/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 2.3941e-04 - loss: -41703852.0000
Epoch 85/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 2.3941e-04 - loss: -43052016.0000
Epoch 86/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 2.3941e-04 - loss: -44427796.0000
Epoch 87/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 2.3941e-04 - loss: -45832660.0000
Epoch 88/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 2.3941e-04 - loss: -47266492.0000
Epoch 89/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 2.3941e-04 - loss: -48728164.0000
Epoch 90/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 2.3941e-04 - loss: -50218760.0000
Epoch 91/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 2.3941e-04 - loss: -51741240.0000
Epoch 92/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 2.3941e-04 - loss: -53292024.0000
Epoch 93/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 2.3941e-04 - loss: -54872728.0000
Epoch 94/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 2.3941e-04 - loss: -56484656.0000
Epoch 95/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 2.3941e-04 - loss: -58127096.0000
Epoch 96/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 2.3941e-04 - loss: -59799944.0000
Epoch 97/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 2.3941e-04 - loss: -61502840.0000
Epoch 98/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 2.3941e-04 - loss: -63234980.0000
Epoch 99/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 2.3941e-04 - loss: -64999416.0000
Epoch 100/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -66797856.0000
Epoch 101/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 2.3941e-04 - loss: -68629928.0000
Epoch 102/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 2.3941e-04 - loss: -70494144.0000
Epoch 103/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 2.3941e-04 - loss: -72387920.0000
Epoch 104/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - accuracy: 2.3941e-04 - loss: -74316008.0000
Epoch 105/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 2.3941e-04 - loss: -76277576.0000
Epoch 106/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 791us/step - accuracy: 2.3941e-04 - loss: -78274056.0000
Epoch 107/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 2.3941e-04 - loss: -80302992.0000
Epoch 108/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 2.3941e-04 - loss: -82364912.0000
Epoch 109/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -84460272.0000
Epoch 110/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 2.3941e-04 - loss: -86591216.0000
Epoch 111/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 2.3941e-04 - loss: -88756576.0000
Epoch 112/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 2.3941e-04 - loss: -90957168.0000
Epoch 113/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -93194344.0000
Epoch 114/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step - accuracy: 2.3941e-04 - loss: -95469928.0000
Epoch 115/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 2.3941e-04 - loss: -97780416.0000
Epoch 116/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 2.3941e-04 - loss: -100126224.0000
Epoch 117/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 2.3941e-04 - loss: -102506680.0000
Epoch 118/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 2.3941e-04 - loss: -104926064.0000
Epoch 119/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 2.3941e-04 - loss: -107380616.0000
Epoch 120/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 2.3941e-04 - loss: -109871344.0000
Epoch 121/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 2.3941e-04 - loss: -112402536.0000
Epoch 122/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 2.3941e-04 - loss: -114971032.0000
Epoch 123/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 2.3941e-04 - loss: -117577760.0000
Epoch 124/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 2.3941e-04 - loss: -120222144.0000
Epoch 125/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 2.3941e-04 - loss: -122903928.0000
Epoch 126/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 2.3941e-04 - loss: -125625184.0000
Epoch 127/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 2.3941e-04 - loss: -128386720.0000
Epoch 128/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 2.3941e-04 - loss: -131187120.0000
Epoch 129/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 2.3941e-04 - loss: -134028272.0000
Epoch 130/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 2.3941e-04 - loss: -136910032.0000
Epoch 131/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 2.3941e-04 - loss: -139832736.0000
Epoch 132/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 2.3941e-04 - loss: -142795136.0000
Epoch 133/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 2.3941e-04 - loss: -145798448.0000
Epoch 134/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 2.3941e-04 - loss: -148842896.0000
Epoch 135/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 2.3941e-04 - loss: -151928192.0000
Epoch 136/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 2.3941e-04 - loss: -155054432.0000
Epoch 137/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 2.3941e-04 - loss: -158219536.0000
Epoch 138/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 2.3941e-04 - loss: -161426816.0000
Epoch 139/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 2.3941e-04 - loss: -164677840.0000
Epoch 140/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -167973264.0000
Epoch 141/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 2.3941e-04 - loss: -171313392.0000
Epoch 142/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -174696112.0000
Epoch 143/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 2.3941e-04 - loss: -178122000.0000
Epoch 144/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 2.3941e-04 - loss: -181590432.0000
Epoch 145/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 2.3941e-04 - loss: -185104272.0000
Epoch 146/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 2.3941e-04 - loss: -188663280.0000
Epoch 147/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 2.3941e-04 - loss: -192265872.0000
Epoch 148/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 2.3941e-04 - loss: -195909904.0000
Epoch 149/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 2.3941e-04 - loss: -199602064.0000
Epoch 150/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 2.3941e-04 - loss: -203341680.0000