In [1]:
import keras
from keras.models import Sequential  
from keras import layers
from keras.layers import Dense  
import numpy
import pandas as pd  

import warnings
warnings.filterwarnings("ignore")

In [2]:
name_columns = ['Sexo', 'Largura', 'Diámetro', 'Altura', 'Whole_weight', 'Shucked_weight', 'Viscera_weight', 'Shell_weight','Anillos']

dataset = pd.read_csv("C:/Users/Jose Manuel/Documents/VisualStudioCode_Workspace/Repo_CEDAPY/CEDAPY_25_26/ANALISIS_DATOS_PYTHON/NOTEBOOKS/EJERCICIOS/RN/abalone.data",
                        delimiter=",", header=None, names=name_columns)
display(dataset)

,Sexo,Largura,Diámetro,Altura,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Anillos
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [3]:
map_target_class = {'M': 0, 'F': 1, 'I':3}
dataset['Sexo']= dataset['Sexo'].map(map_target_class)
dataset.head()

,Sexo,Largura,Diámetro,Altura,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Anillos
0,0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,0,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,1,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,0,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,3,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [4]:
X = dataset.iloc[:,0:8]  
Y = dataset.iloc[:,8]

In [5]:
print(X.shape)
print(Y.shape)

(4177, 8)
(4177,)

In [ ]:
model2 = keras.Sequential([
    keras.layers.Input(shape=(8,)),
    keras.layers.Dense(12, activation='relu'),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(1, activation='linear')    
])

In [7]:
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
training_model = model2.fit(X, Y, epochs=150, batch_size=10)

Epoch 1/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 858us/step - accuracy: 2.3941e-04 - loss: -292.7582
Epoch 2/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 2.3941e-04 - loss: -4477.8677
Epoch 3/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 2.3941e-04 - loss: -18471.1309
Epoch 4/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 2.3941e-04 - loss: -46381.5000
Epoch 5/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 2.3941e-04 - loss: -90896.3203
Epoch 6/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 2.3941e-04 - loss: -153523.9688
Epoch 7/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 2.3941e-04 - loss: -235639.5938
Epoch 8/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 2.3941e-04 - loss: -338527.8750
Epoch 9/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 2.3941e-04 - loss: -463328.8125
Epoch 10/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 2.3941e-04 - loss: -610809.4375
Epoch 11/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -781606.1875
Epoch 12/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 2.3941e-04 - loss: -976933.9375
Epoch 13/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 2.3941e-04 - loss: -1197800.7500
Epoch 14/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -1445368.1250
Epoch 15/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -1719987.2500
Epoch 16/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -2023012.0000
Epoch 17/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -2355405.5000
Epoch 18/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 2.3941e-04 - loss: -2718001.0000
Epoch 19/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -3111815.0000
Epoch 20/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -3538008.0000
Epoch 21/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 2.3941e-04 - loss: -3997682.2500
Epoch 22/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 2.3941e-04 - loss: -4491903.0000
Epoch 23/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -5022016.0000
Epoch 24/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -5588683.5000
Epoch 25/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 2.3941e-04 - loss: -6192269.5000
Epoch 26/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 2.3941e-04 - loss: -6833644.5000
Epoch 27/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 2.3941e-04 - loss: -7514210.0000
Epoch 28/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 2.3941e-04 - loss: -8235602.5000
Epoch 29/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -8998758.0000
Epoch 30/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -9804641.0000
Epoch 31/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 2.3941e-04 - loss: -10653862.0000
Epoch 32/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -11546559.0000
Epoch 33/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -12484261.0000
Epoch 34/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -13468764.0000
Epoch 35/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -14501051.0000
Epoch 36/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -15582309.0000
Epoch 37/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -16711798.0000
Epoch 38/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -17891192.0000
Epoch 39/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 2.3941e-04 - loss: -19123668.0000
Epoch 40/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 2.3941e-04 - loss: -20407314.0000
Epoch 41/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 2.3941e-04 - loss: -21743876.0000
Epoch 42/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 2.3941e-04 - loss: -23134874.0000
Epoch 43/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 2.3941e-04 - loss: -24581472.0000
Epoch 44/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 2.3941e-04 - loss: -26085546.0000
Epoch 45/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 2.3941e-04 - loss: -27645930.0000
Epoch 46/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 2.3941e-04 - loss: -29265418.0000
Epoch 47/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 2.3941e-04 - loss: -30943156.0000
Epoch 48/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 2.3941e-04 - loss: -32679638.0000
Epoch 49/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 2.3941e-04 - loss: -34477808.0000
Epoch 50/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 2.3941e-04 - loss: -36338248.0000
Epoch 51/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 2.3941e-04 - loss: -38260684.0000
Epoch 52/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 2.3941e-04 - loss: -40246524.0000
Epoch 53/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 850us/step - accuracy: 2.3941e-04 - loss: -42297832.0000
Epoch 54/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 2.3941e-04 - loss: -44415272.0000
Epoch 55/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 2.3941e-04 - loss: -46598724.0000
Epoch 56/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 2.3941e-04 - loss: -48847960.0000
Epoch 57/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 2.3941e-04 - loss: -51167272.0000
Epoch 58/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 2.3941e-04 - loss: -53557532.0000
Epoch 59/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 2.3941e-04 - loss: -56018068.0000
Epoch 60/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 2.3941e-04 - loss: -58549788.0000
Epoch 61/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 2.3941e-04 - loss: -61151076.0000
Epoch 62/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 2.3941e-04 - loss: -63826608.0000
Epoch 63/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 2.3941e-04 - loss: -66576808.0000
Epoch 64/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 2.3941e-04 - loss: -69401640.0000
Epoch 65/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 2.3941e-04 - loss: -72305376.0000
Epoch 66/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 2.3941e-04 - loss: -75286280.0000
Epoch 67/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 2.3941e-04 - loss: -78345160.0000
Epoch 68/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 2.3941e-04 - loss: -81485904.0000
Epoch 69/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 2.3941e-04 - loss: -84706320.0000
Epoch 70/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 2.3941e-04 - loss: -88003960.0000
Epoch 71/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 2.3941e-04 - loss: -91384280.0000
Epoch 72/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 2.3941e-04 - loss: -94848640.0000
Epoch 73/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 2.3941e-04 - loss: -98395080.0000
Epoch 74/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 2.3941e-04 - loss: -102028624.0000
Epoch 75/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 2.3941e-04 - loss: -105751504.0000
Epoch 76/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 2.3941e-04 - loss: -109558584.0000
Epoch 77/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -113451768.0000
Epoch 78/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 2.3941e-04 - loss: -117431968.0000
Epoch 79/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 2.3941e-04 - loss: -121499864.0000
Epoch 80/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 2.3941e-04 - loss: -125659072.0000
Epoch 81/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 2.3941e-04 - loss: -129918792.0000
Epoch 82/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 2.3941e-04 - loss: -134266576.0000
Epoch 83/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 2.3941e-04 - loss: -138703760.0000
Epoch 84/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -143241632.0000
Epoch 85/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 2.3941e-04 - loss: -147870720.0000
Epoch 86/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 2.3941e-04 - loss: -152596928.0000
Epoch 87/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 2.3941e-04 - loss: -157422416.0000
Epoch 88/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 2.3941e-04 - loss: -162344656.0000
Epoch 89/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 2.3941e-04 - loss: -167368192.0000
Epoch 90/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 2.3941e-04 - loss: -172487456.0000
Epoch 91/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 2.3941e-04 - loss: -177707648.0000
Epoch 92/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 2.3941e-04 - loss: -183030528.0000
Epoch 93/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 2.3941e-04 - loss: -188455744.0000
Epoch 94/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 2.3941e-04 - loss: -193988352.0000
Epoch 95/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 2.3941e-04 - loss: -199618976.0000
Epoch 96/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 2.3941e-04 - loss: -205358080.0000
Epoch 97/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 2.3941e-04 - loss: -211198160.0000
Epoch 98/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 2.3941e-04 - loss: -217148160.0000
Epoch 99/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 2.3941e-04 - loss: -223212560.0000
Epoch 100/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 2.3941e-04 - loss: -229390896.0000
Epoch 101/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 2.3941e-04 - loss: -235674384.0000
Epoch 102/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 2.3941e-04 - loss: -242066016.0000
Epoch 103/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -248574832.0000
Epoch 104/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -255192512.0000
Epoch 105/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 2.3941e-04 - loss: -261925952.0000
Epoch 106/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 2.3941e-04 - loss: -268770688.0000
Epoch 107/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 2.3941e-04 - loss: -275734144.0000
Epoch 108/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 2.3941e-04 - loss: -282811008.0000
Epoch 109/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 2.3941e-04 - loss: -290004832.0000
Epoch 110/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 850us/step - accuracy: 2.3941e-04 - loss: -297318048.0000
Epoch 111/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 2.3941e-04 - loss: -304765088.0000
Epoch 112/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 2.3941e-04 - loss: -312327584.0000
Epoch 113/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 854us/step - accuracy: 2.3941e-04 - loss: -320009376.0000
Epoch 114/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 2.3941e-04 - loss: -327813056.0000
Epoch 115/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 2.3941e-04 - loss: -335731232.0000
Epoch 116/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -343774720.0000
Epoch 117/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 2.3941e-04 - loss: -351949696.0000
Epoch 118/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 2.3941e-04 - loss: -360245824.0000
Epoch 119/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 2.3941e-04 - loss: -368669056.0000
Epoch 120/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 2.3941e-04 - loss: -377227904.0000
Epoch 121/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 2.3941e-04 - loss: -385919808.0000
Epoch 122/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 2.3941e-04 - loss: -394739296.0000
Epoch 123/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 2.3941e-04 - loss: -403679936.0000
Epoch 124/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 2.3941e-04 - loss: -412762176.0000
Epoch 125/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 2.3941e-04 - loss: -421973504.0000
Epoch 126/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 2.3941e-04 - loss: -431314816.0000
Epoch 127/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 2.3941e-04 - loss: -440789376.0000
Epoch 128/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 2.3941e-04 - loss: -450389792.0000
Epoch 129/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 2.3941e-04 - loss: -460130560.0000
Epoch 130/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 2.3941e-04 - loss: -470007680.0000
Epoch 131/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 2.3941e-04 - loss: -480026080.0000
Epoch 132/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 2.3941e-04 - loss: -490187168.0000
Epoch 133/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 2.3941e-04 - loss: -500490720.0000
Epoch 134/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 2.3941e-04 - loss: -510936352.0000
Epoch 135/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 2.3941e-04 - loss: -521527136.0000
Epoch 136/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 2.3941e-04 - loss: -532275392.0000
Epoch 137/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 2.3941e-04 - loss: -543166592.0000
Epoch 138/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 2.3941e-04 - loss: -554194432.0000
Epoch 139/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 2.3941e-04 - loss: -565355136.0000
Epoch 140/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 2.3941e-04 - loss: -576659008.0000
Epoch 141/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 2.3941e-04 - loss: -588108288.0000
Epoch 142/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 2.3941e-04 - loss: -599704960.0000
Epoch 143/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 2.3941e-04 - loss: -611466752.0000
Epoch 144/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 2.3941e-04 - loss: -623371840.0000
Epoch 145/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 2.3941e-04 - loss: -635429312.0000
Epoch 146/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 2.3941e-04 - loss: -647653120.0000
Epoch 147/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 2.3941e-04 - loss: -660026368.0000
Epoch 148/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 2.3941e-04 - loss: -672541952.0000
Epoch 149/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 2.3941e-04 - loss: -685219008.0000
Epoch 150/150
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 2.3941e-04 - loss: -698052096.0000

In [10]:
model2.evaluate(X, Y, batch_size=32)

131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 2.3941e-04 - loss: -704541696.0000

[-704541696.0, 0.00023940627579577267]