# K-NN para regresión. EJERCICIO GUIADO    

La **Regresión del Vecino más Cercano** es un método no paramétrico usado para problemas de predicción. Opera sobre la premisa de que valores de entrada similares probablemente producen valores de salida similares.    
En el contexto de la regresión, KNN toma un número específico (K) de los puntos de datos (vecinos) más cercanos y promedia sus valores para hacer una predicción.

## El regresor K-NN en Scikit-Learn    

En Sklearn, la regresión KNN se implementa a través de la clase KNeighborsRegressor.   
```
from sklearn.neighbors import KNeighborsRegressor
```   

A continuación se muestra un ejemplo práctico de uso de este regresor:

In [3]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor

In [6]:
# Cargar el conjunto de datos
boston = pd.read_csv('/home/jordi/Documentos/Ribera/Curso_25_26/CEDAPY/REPOS/CEDAPY_25_26/ANALISIS_DATOS_PYTHON/DATASETS/bostonDataset.csv')   
boston.head()

,TOWN,TRACT,LON,LAT,MEDV,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO
0,Nahant,2011,-70.955,42.2550,24.0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3
1,Swampscott,2021,-70.950,42.2875,21.6,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8
2,Swampscott,2022,-70.936,42.2830,34.7,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8
3,Marblehead,2031,-70.928,42.2930,33.4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7
4,Marblehead,2032,-70.922,42.2980,36.2,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7

Campos del dataset Boston:   

- CRIM - índice de delincuencia per cápita por ciudad
- ZN - proporción de suelo residencial para parcelas de más de 25.000 pies cuadrados
- INDUS - proporción de acres comerciales no minoristas por ciudad
- CHAS - Variable ficticia del río Charles (= 1 si la zona linda con el río; 0 en caso contrario)
- NOX - concentración de óxidos nítricos (partes por 10 millones)
- RM - número medio de habitaciones por vivienda
- EDAD - proporción de unidades ocupadas por sus propietarios construidas antes de 1940
- DIS - distancias ponderadas a cinco centros de empleo de Boston
- RAD - índice de accesibilidad a autopistas radiales
- TAX - tipo del impuesto sobre bienes inmuebles por cada 10.000 dólares
- PTRATIO - ratio alumnos-profesor por ciudad
- B - 1000(Bk - 0,63)^2 donde Bk es la proporción de negros por ciudad
- LSTAT - % de estatus inferior de la población
- MEDV - Valor medio de las viviendas ocupadas por sus propietarios en 1000 $ (**objetivo**)

In [ ]:
X = boston.drop(['MEDV','TOWN'], axis=1)  # Características (todas las columnas excepto la objetivo y 'TOWN') 
y = boston['MEDV']  # Columna objetivo

In [12]:
# Dividir el conjunto de datos en conjuntos de capacitación y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Aplicar la regresión KNN
knn_regressor = KNeighborsRegressor(n_neighbors=3)
knn_regressor.fit(X_train, y_train)
predictions = knn_regressor.predict(X_test)

In [14]:
 
# Evaluar el modelo
print('Puntuación:', knn_regressor.score(X_test, y_test))

Puntuación: 0.6940623781786679

## EJERCICIO

1. Usa GridSearchCV para ajustar los hiperparámetros del modelo K-NN Regresor del ejemplo anterior para intentar mejorar su puntuación.

2. Realiza un análisis de datos y aplica el modelo regresor K-NN con el dataset **Advertising"** intentando calcular las ventas ("sales") según el gasto dedicado en campañas de marketing en los 3 medios siguientes: Televisión, Radio y Prensa.

In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor

In [2]:
advertising = pd.read_csv('/home/jordi/Documentos/Ribera/Curso_25_26/CEDAPY/REPOS/CEDAPY_25_26/ANALISIS_DATOS_PYTHON/DATASETS/Advertising.csv')   
advertising.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9