### Ejercicio Dataset Vinos

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
file = "C:/Users/Jose Manuel/Documents/VisualStudioCode_Workspace/Repo_CEDAPY/CEDAPY_25_26/ANALISIS_DATOS_PYTHON/DATASETS/wines_SPA.csv"
df_wines = pd.read_csv(file, sep=',', engine= 'python')
df_wines.head(5)

,winery,wine,year,rating,num_reviews,country,region,price,type,body,acidity
0,Teso La Monja,Tinto,2013,4.9,58,Espana,Toro,995.00,Toro Red,5.0,3.0
1,Artadi,Vina El Pison,2018,4.9,31,Espana,Vino de Espana,313.50,Tempranillo,4.0,2.0
2,Vega Sicilia,Unico,2009,4.8,1793,Espana,Ribera del Duero,324.95,Ribera Del Duero Red,5.0,3.0
3,Vega Sicilia,Unico,1999,4.8,1705,Espana,Ribera del Duero,692.96,Ribera Del Duero Red,5.0,3.0
4,Vega Sicilia,Unico,1996,4.8,1309,Espana,Ribera del Duero,778.06,Ribera Del Duero Red,5.0,3.0

In [13]:
print(df_wines.shape)

(7500, 11)

- Vemos que el dataset tiene un total de 7500 registros en 11 columnas.

In [14]:
df_wines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   winery       7500 non-null   object
 1   wine         7500 non-null   object
 2   year         7498 non-null   object
 3   rating       7500 non-null   float64
 4   num_reviews  7500 non-null   int64
 5   country      7500 non-null   object
 6   region       7500 non-null   object
 7   price        7500 non-null   float64
 8   type         6955 non-null   object
 9   body         6331 non-null   float64
 10  acidity      6331 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 644.7+ KB

- Podemos observar el tipo de datos viendo los que son númericos de los que son objetos.
- Se observa también de que las columnas tipo, cuerpo y acidez presentan bastantes datos que en principio parecen nulos

In [17]:
null_type = df_wines['type'].isnull().sum()
null_body = df_wines['body'].isnull().sum()
null_acidity = df_wines['acidity'].isnull().sum()
print(f"Nulos de tipo: {null_type}\nNulos de cuerpo: {null_body}\nNulos de acidez: {null_acidity}")

Nulos de tipo: 545
Nulos de cuerpo: 1169
Nulos de acidez: 1169

In [15]:
df_wines.describe()

            rating   num_reviews        price         body      acidity
count  7500.000000   7500.000000  7500.000000  6331.000000  6331.000000
mean      4.254933    451.109067    60.095822     4.158427     2.946612
std       0.118029    723.001856   150.356676     0.583352     0.248202
min       4.200000     25.000000     4.990000     2.000000     1.000000
25%       4.200000    389.000000    18.900000     4.000000     3.000000
50%       4.200000    404.000000    28.530000     4.000000     3.000000
75%       4.200000    415.000000    51.350000     5.000000     3.000000
max       4.900000  32624.000000  3119.080000     5.000000     3.000000

- Podemos ver que hay una gran desviación entre los precios donde el mínimo esta en 5€ y el máximo en 3.119€ lo que propicia que la media no sea muy representativa. Habra que mirar como estan distribuidos eso precios.
- Por el contrario los datos de rating, cuerpo y acidez no son tan dispersos, por lo que los datos de media son más representativos y fiables.

In [ ]:
# Configurar Pandas para mostrar todas las filas y columnas
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
wines_type = df_wines.groupby('type')['wine'].count().sort_values(ascending=False)
print(wines_type)

type
Rioja Red               2357
Ribera Del Duero Red    1407
Red                      864
Priorat Red              674
Toro Red                 296
Tempranillo              291
Sherry                   274
Albarino                 252
Mencia                   235
Rioja White               92
Pedro Ximenez             35
Grenache                  35
Cava                      33
Verdejo                   27
Monastrell                18
Montsant Red              17
Syrah                     15
Chardonnay                13
Cabernet Sauvignon        11
Sparkling                  5
Sauvignon Blanc            4
Name: wine, dtype: int64

- Con este resultado podemos ver, que los tipos de vinos más presentes en el dataset son Rioja y Ribera del Duero, mientras que el tipo de Sauvignon blanco apenas hay datos del mismo.

In [28]:
bodegas = df_wines.groupby('winery')['wine'].count().sort_values(ascending=False)
print(bodegas)

winery
Contino                                             457
Artadi                                              261
La Rioja Alta                                       254
Sierra Cantabria                                    237
Matarromera                                         232
Vina Pedrosa                                        230
Imperial                                            228
Losada                                              227
Ramon Bilbao                                        225
Sei Solo                                            225
Portal del Priorat                                  225
Matsu                                               224
Campillo                                            223
Lustau                                              223
Bodegas La Horra                                    223
La Vicalanda                                        223
Conreria d'Scala Dei                                223
Mar de Frades                                       222
Mustiguillo                                         222
Clos Pons                                           220
Enrique Mendoza                                     220
Binigrau                                            220
Ramon do Casar                                      220
Vinedos de Paganos                                  175
Vega Sicilia                                         97
Remirez de Ganuza                                    79
Alvaro Palacios                                      48
Marques de Murrieta                                  33
Dominio de Pingus                                    31
Martinet                                             30
Abadia Retuerta                                      27
Vina Sastre                                          25
Emilio Moro                                          25
Toro Albala                                          23
Bodegas Roda                                         23
Muga                                                 23
Marques de Riscal                                    21
Bodega Contador (Benjamin Romeo)                     21
Clos Mogador                                         20
Familia Torres                                       19
Pago de Los Capellanes                               19
Bodegas Mauro                                        18
Teso La Monja                                        17
Alion                                                16
Arzuaga                                              16
Bodegas Mas Alta                                     14
Bodegas Valduero                                     14
Pintia                                               14
Tinto Pesquera                                       14
Bodega Numanthia                                     14
Hacienda Monasterio                                  14
Allende                                              14
Bodegas El Nido                                      13
Mas Doix                                             13
Remelluri                                            13
R. Lopez de Heredia                                  13
Carmelo Rodero                                       13
Recaredo                                             12
Aalto                                                12
Castillo Perelada                                    12
Pago de Carraovejas                                  11
Vinicola Real                                        11
Clos Erasmus                                         11
Protos                                               11
Benjamin de Rothschild - Vega Sicilia                10
Scala Dei                                            10
Gramona                                              10
Ferrer Bobet                                         10
Alto Moncayo                                         10
Terroir Al Limit Soc. Lda                            10
Lan                                                   9
Anima Negra                                           9
Enate                                                 9
Bodegas San Roman                                     9
Pujanza                                               8
Tomas Postigo                                         8
Vall Llach                                            8
Descendientes de J. Palacios                          8
Bodegas Amaren                                        8
Dominio del Aguila                                    8
Marques de Caceres                                    8
Bodegas Faustino                                      7
Mas d'en Gil                                          7
Vizcarra                                              7
Ossian                                                7
Juan Gil                                              7
Dominio de Atauta                                     7
Senorio de San Vicente                                6
Tridente                                              6
Gomez Cruzado                                         6
Espectacle del Montsant                               6
Costers del Siurana                                   6
Cims de Porrera                                       6
Volver                                                6
Marques de Vargas                                     6
Telmo Rodriguez                                       6
Agusti Torello Mata                                   5
Dominio de Es                                         5
Garmon                                                5
Finca Torremilanos                                    5
Gonzalez-Byass                                        5
Dominio del Bendito                                   5
Bosque de Matasnos                                    5
Jimenez-Landi                                         5
Bodegas Ximenez-Spinola                               5
Pago de Vallegarcia                                   5
Ordonez                                               5
Bodegas Tradicion                                     5
Bodegas 6o Elemento - Vino Sexto Elemento             5
Rafael Palacios                                       5
Atalaya                                               5
Osborne                                               5
Valderiz                                              4
Torre de Ona                                          4
Tobia                                                 4
Tresmano - Tr3smano                                   4
Vinas del Vero                                        4
Vina Pomal                                            4
Altanza                                               4
Quinta Sardonia                                       4
Terras Gauda                                          4
Terra Remota                                          4
Territorio Luthier                                    4
Alta Alella                                           4
Chivite                                               4
Romate                                                4
Belondrade                                            4
Bodegas Celler Francisco Castillo - Clos Dominic      4
Abel Mendoza Monge                                    4
Williams & Humbert                                    4
Vinyes Domenech                                       4
Finca Villacreces                                     4
Figuero                                               4
Dehesa de Los Canonigos                               4
Jaro                                                  4
De Moya                                               4
Huerta de Albala                                      4
Casa Castillo                                         4
Clos Galena                                           4
Clos Figueras                                         4
Marques de Grinon                                     4
Jose Pariente                                         4
Dominio de Cair                                       4
Adama Wines                                           4
Miguel Merino                                         4
Oxer Wines                                            4
Pazo Senorans                                         4
Bodegas Naluar & Acediano                             4
Merum Priorati                                        4
Castell d'Encus                                       4
Los Aguilares                                         4
Pradorey                                              4
Bodegas Vilano                                        4
Luis Canas                                            4
Castano                                               4
Morca                                                 4
Arinzano                                              3
Altos de Rioja                                        3
Venus la Universal                                    3
VALENCISO                                             3
Raul Perez                                            3
Bodega Tameran                                        3
Sebio                                                 3
Barahonda                                             3
Ausas                                                 3
Baigorri                                              3
Valdespino                                            3
Antidoto                                              3
Valquejigoso                                          3
Penafiel                                              3
Ostatu                                                3
Nin-Ortiz                                             3
Pedralonga                                            3
Carlos Moro                                           3
Montecastro                                           3
Monte Real                                            3
Legaris                                               3
Llopart                                               3
Cepa 21                                               3
Castillo de Cuzcurrita                                3
Cervoles                                              3
Comenge                                               3
Clos d'Agon                                           3
Cruz de Alba                                          3
Gutierrez de la Vega                                  3
Hacienda Solano                                       3
Dehesa del Carrizal                                   3
Finca Rio Negro                                       3
Equipo Navazos                                        3
Ysios                                                 3
Enric Soler                                           3
Abadal                                                3
Alvaro Domecq                                         2
Alvear                                                2
Anayon                                                2
Venta Las Vacas                                       2
Vinedos Hermanos Hernaiz                              2
Zifar                                                 2
El Maestro Sierra                                     2
El Regajal                                            2
Eulogio Pomares                                       2
Beronia                                               2
Bodega Campo Eliseo                                   2
Bodega Elias Mora                                     2
Bodega Juan Carlos Sancha                             2
Bodega Otazu                                          2
Aster                                                 2
Astrales                                              2
Atlan & Artisan                                       2
Finca Moncloa                                         2
Finca Valpiedra                                       2
Dominio do Bibei                                      2
El Coto                                               2
Sangenis I Vaque                                      2
Sara Perez y Rene Barbier                             2
St. Petroni                                           2
Taron                                                 2
Tarsus                                                2
Rodriguez de Vera                                     2
Sacristia AB                                          2
Bodega Ribas                                          2
Bodega Tesalia                                        2
Bodega de Bardos                                      2
Bodegas Aragonesas                                    2
Bodegas Luis Perez                                    2
Bodegas Ochoa                                         2
Perinet                                               2
Pinea                                                 2
Quinta de la Quietud                                  2
Real de Asua                                          2
Resalte                                               2
Francisco Barona                                      2
Habla                                                 2
Hacienda Lopez de Haro                                2
Harveys                                               2
Pago Calzadilla                                       2
Pago de Larrainzar                                    2
Pazo Barrantes                                        2
Bodegas Frontaura                                     2
Bodegas Frontonio                                     2
Bodegas Gama                                          2
Hispano Suizas                                        2
Javier Sanz Viticultor                                2
De Muller                                             2
Ontanon                                               2
Orben                                                 2
Bodegas Reyes                                         2
Can Rafols dels Caus                                  2
Mestres                                               2
Neo                                                   2
Cal Batllet - Celler Ripoll Sans                      2
Cal Pla                                               2
Celler de Capcanes                                    2
Marco Abella                                          2
Marques de Tomares                                    2
Marti Fabra                                           2
Martin Codax                                          2
Do Ferreiro (Bodegas Gerardo Mendez)                  2
Jesus Madrazo                                         2
Jorge Ordonez                                         2
Josep Grau Viticultor                                 2
Juan Pinero                                           2
Juve & Camps                                          2
Chozas Carrascal                                      2
Cillar de Silos                                       2
Leda                                                  2
Llanos Negros                                         2
Lopez Cristobal                                       2
Luis A. Rodriguez Vazquez                             2
Cartoixa de Montsalvat                                2
Casa Rojo                                             2
Albet i Noya                                          2
Vivanco                                               2
Avancia                                               2
Avgvstvs                                              2
Trus                                                  2
Ukan Winery                                           2
Valtravieso                                           2
Alonso del Yerro                                      2
Altos del Enebro                                      1
Valserrano                                            1
Valdubon                                              1
Valdelosfrailes                                       1
Valdecuevas                                           1
Uvaguilera Aguilera                                   1
Baluarte                                              1
Balandro                                              1
Azpilicueta                                           1
Attis                                                 1
Xaloc                                                 1
Vivaltus                                              1
Virgen de la Asuncion                                 1
Vinyes dels Aspres                                    1
Vinyes del Terrer                                     1
Vins Miquel Gelabert                                  1
Vinos Sanz                                            1
Alonso & Pedrajo                                      1
Algueira                                              1
Albamar                                               1
Adega Familiar Eladio Pineiro                         1
Acustic Celler                                        1
AGE                                                   1
A Coroa                                               1
Castell Miquel                                        1
Casal de Arman                                        1
Loxera                                                1
Loess                                                 1
Lar de Paula                                          1
Lambuena                                              1
Lagar de Sabariz                                      1
Ladairo                                               1
La Vinya del Vuit                                     1
Condado de Haza                                       1
Collbaix Celler El Moli                               1
Codorniu                                              1
La Val                                                1
La Unica                                              1
La Legua                                              1
Jorge Piernas                                         1
Joan d'Anguera                                        1
Joan Simo                                             1
Mas Bertran                                           1
Martinez Lacuesta                                     1
Marta Mate                                            1
Marques de la Concordia                               1
Marques de Burgos                                     1
Mandia Vell                                           1
M. Antonio de la Riva                                 1
Cerro San Cristobal                                   1
Cepas Familiares                                      1
Cayetano del Pino                                     1
Castell del Remei                                     1
Can Bas                                               1
Can Axartell                                          1
Callejuela                                            1
Ca l'Apotecari                                        1
Buil & Gine                                           1
Briego                                                1
Breca                                                 1
Mauro Estevez                                         1
Mas del Serral                                        1
Mas de les Pereres                                    1
Mas Que Vinos                                         1
Mas Perinet                                           1
Mas Llunes                                            1
Mas Blanch I Jove                                     1
Navajas                                               1
Naia                                                  1
Museum                                                1
Murviedro                                             1
Murua                                                 1
Monteabellon                                          1
Monovar                                               1
Mocen                                                 1
Milsetentayseis                                       1
Micro Bio (MicroBio)                                  1
Carlos Serres                                         1